name: "Authelia Authentication"
guid: "6bb8dbba-2aaa-4b19-9da4-f3bbb6c44091"
imageUrl: "https://raw.githubusercontent.com/nikarh/jellyfin-plugin-authelia/master/logo.png"
version: "15"
targetAbi: "10.11.0.0"
framework: "net9.0"
owner: "nikarh"
overview: "Authenticate users via Authelia"
description: |
  Authenticate your Jellyfin with Authelia, and optionally create users who do not yet exist automatically.

  This plugin uses Authelia HTTP API for authentication. Unlike with an SSO plugin, this allows using the existing Jellyfin login UI and API, which is compatible with all existing Jellyfin clients.
  The main drawback of this approach is that 2FA is not supported.
category: "Authentication"
artifacts:
  - "Authelia-Auth.dll"
changelog: |2-
  ### Changed
  - Updated for Jellyfin 10.11
